---
- hosts: all
  remote_user: jonathan
  become: true
  tasks:
    - name: add zsh
      apt:
        update_cache: yes
        name: zsh
    - name: set shell to zsh
      user: name=jonathan shell=/bin/zsh
  roles:
    - ANXS.hostname
    - geerlingguy.firewall
    - geerlingguy.security
