---
- hosts: all
  remote_user: jonathan
  become: true

  tasks:
    - name: remove nginx default config
      file:
        path: /etc/nginx/sites-available/default
        state: absent
    
    - name: add .htpasswd
      copy:
        src: .htpasswd
        dest: /etc/nginx/.htpasswd
        owner: root
        group: root
        mode: 0755
        decrypt: yes

  vars:
    nginx_configs:
      proxy:
        - proxy_cache_path /var/www/cache keys_zone=one:10m
    nginx_sites:
      roitgrund:
          - listen 443 ssl http2 default_server
          - ssl_certificate /home/acme/certs/cert.pem
          - ssl_certificate_key /home/acme/certs/key.pem
          - ssl_session_timeout 1d
          - ssl_session_cache shared:SSL:50m
          - ssl_session_tickets off
          - ssl_protocols TLSv1.2
          - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
          - ssl_prefer_server_ciphers on
          - proxy_cache one
          - server_name {{ inventory_hostname }}
          - location = /passmein { return 301 /passmein/; }
          - location /passmein/ { proxy_pass http://localhost:8000/; }
          - location = /chinema { return 301 /chinema/; }
          - location /chinema/ { proxy_pass http://localhost:8001; proxy_set_header Host $http_host; proxy_set_header X-Forwarded-Proto $scheme;}
          - location = /discogs { return 301 /discogs/; }
          - location /discogs/ { proxy_pass http://localhost:3000; }
          - location = /chip16 { return 301 /chip16/; }
          - location / { return 301 https://jroitgrund.github.io/; }
          - location /deluge { proxy_pass http://localhost:8112/; proxy_set_header X-Deluge-Base "/deluge/"; add_header X-Frame-Options SAMEORIGIN; }
          - location = /downloads { return 301 /downloads/; }
          - location /downloads/ { alias /var/lib/deluged/Downloads/; autoindex on; auth_basic "Welcome" ; auth_basic_user_file /etc/nginx/.htpasswd; }

  roles:
    - jdauphant.nginx
