---
- hosts: all
  remote_user: jonathan
  become: true

  tasks:
    - name: copy html dir
      copy:
        src: html
        dest: /var/www
        owner: www-data
        group: www-data
        directory_mode: 02750
        mode: 0640

  vars:
    nginx_sites:
      roitgrund:
          - listen 443 ssl http2 default_server
          - ssl_certificate /home/acme/certs/cert.pem
          - ssl_certificate_key /home/acme/certs/key.pem
          - ssl_session_timeout 1d
          - ssl_session_cache shared:SSL:50m
          - ssl_session_tickets off
          - ssl_protocols TLSv1.2
          - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
          - ssl_prefer_server_ciphers on
          - server_name {{ inventory_hostname }}
          - root /var/www/html
          - index index.html
          - location = /passmein { return 301 /passmein/; }
          - location /passmein/ { proxy_pass http://localhost:8000/; }
          - location = /chinema { return 301 http://chinema/; }
          - location /chinema/ { proxy_pass http://localhost:8001; proxy_set_header Host $http_host; proxy_set_header X-Forwarded-Proto $scheme;}

  roles:
    - jdauphant.nginx
