---
- hosts: workers
  remote_user: jonathan
  become: true
  tasks:
    - name: "download dokku install script"
      args:
        creates: /usr/bin/dokku
      command: wget https://raw.githubusercontent.com/dokku/dokku/v0.9.4/bootstrap.sh
    - name: "install dokku"
      args:
        creates: /usr/bin/dokku
      command: DOKKU_TAG=v0.9.4 bash /home/jonathan/bootstrap.sh
    - name: "remove dokku install script"
      args:
        creates: /usr/bin/dokku
      command: rm bootstrap.sh
  roles: []
